### PR TITLE
Add system-style macOS icon

### LINKED ISSUE #322: Add consistent macOS app icon
hey, are y'all interested in using a macOS icon that's consistent with the actual macOS icon style? I don't see any previous discussion on the repo about it so I'm opening an issue for it.

the easiest solution would be something like this:

<details><summary>App icon concept</summary>
Cinny Desktop white-on-black circular logo within a macOS square-shaped icon on a white background
</details>

<details><summary>App icon concept with official macOS icon design grid</summary>
Cinny Desktop white-on-black circular logo within a macOS square-shaped icon on a white background, with a grid superimposed on it showing the circular logo perfectly sized to match the outermost circular alignment guide
</details>

I'll open a PR with this icon soon™, though would love some guidance on if (and if so, where) you'd like the source file to exist. based on the official [macOS Production Templates](https://developer.apple.com/design/resources/#macos-apps) for app icons, tossed it together in Sketch.

### PR DESCRIPTION
**Pull request by iLynxcat**
### Description

This adds a proper system-style icon to fit in with macOS' icon style that's been adopted since Big Sur. In my original issue #322 I offered to include the original Sketch file for this but not sure where/if it fits in the repo or matters whatsoever to the project's maintainers.

Fixes #322

Preview app displaying the highest resolution version of the Cinny app. A white rounded square contains a black circular vector silhouette of a bird.

#### Type of change

_This PR does not include any functionality change to the app and is purely cosmetic. Marking it as "new feature" because it's the best fit._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

_This PR does not include any code so I'm checking these off anyway..._

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by iLynxcat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Neved4** [comment]
@iLynxcat This is cool! LGTM!

**Comment by stefanlight8** [comment]
Can you share .icns file?

**Comment by iLynxcat** [comment]
> Can you share .icns file?

The .icns file is included in this PR

**Comment by iLynxcat** [comment]
Closing since there has been no activity from maintainers since opening — feel free to comment or reopen if this is considered

**Pull request closed without merging**
