### PR TITLE
Systray 2

### PR DESCRIPTION
**Pull request by StevenDoesStuffs**
### Description

Same as https://github.com/cinnyapp/cinny-desktop/pull/128, but with changes stolen from https://github.com/greentore/greeny-desktop/pull/1. 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by StevenDoesStuffs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by serxka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by StevenDoesStuffs** [comment]
Now that I'm actually using this, I've got two ideas:
1. There needs to be a way to toggle the systray. From what I can tell, the desktop app is just a wrapper around the webapp, so putting that toggle in the GUI sounds difficult. Maybe a `--tray` arg? But then we need multiple .desktop files :/, and that also means we have no way of storing the setting. 
2. Usually with systray apps, there's some sort of minimize on startup. Same difficulties as above apply.

Any ideas on how to deal with those issues? I don't really know much about tauri so maybe there's a feature here that could help.

**Comment by daegalus** [comment]
So I have been patiently following along for any sort of tray icon support because using Cinny on Desktop without it has been annoying.

I just wanted to chime in and suggest that we don't scope creep.

Is it absolutely necessary to toggle or configure the system tray at this point in time? System tray things can be hidden or ignored at the window manager level. It is not super urgent to get it in this PR, maybe it can come in a second PR later.

To answer your questions @StevenDoesStuffs 

1. Maybe at first put the toggle in a menu of the desktop wrapper? you can have it automatically hidden, pressing ALT can show it. Its how most desktop chat apps behave. Slack, Discord, Webcord (which is just a custom wrapper around web discord for better compatibility). Because you are correct, that to make a nice toggle, you need to use the provided Tauri/Javascript interop facilities to call functions on the rust side from the JS side (webapp). This would mean that there will need to be a bit of JS code in the webapp that checks for Tauri or desktop mode (could be a global variable that defaults to false, but set to true by Tauri. That then surfaces a toggle. Here is documentation on how to call rust from the frontend: https://tauri.app/v1/guides/features/command
2. Minimize on startup can be done purely through Tauri/Rust side of things. The Desktop portion of the app can have it's own config file, or it can read a shared config file with the webapp, either way, it can deal with minimize on startup itself. 
 
1) Check config file for setting
2) minimize immediately if setting set from Tauri side. 

```
let window = app.get_window("main").unwrap();
window.hide().unwrap();
``` 
just call that or equivalent on load if setting is set.

Either way, we need to decide on scope, because there are tons of features and tickets relying on a system tray icon, or being able to run in the background with a hidden window.

Minimize to systray on startup can be postponed to a later PR. Configuring the system tray usage can be done entirely through Desktop app menus at first if needed.

**Review by kfiven — APPROVED** [review]

**Pull request merged**
